# Generated by Django 5.1.4 on 2025-01-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_hosteluser_date_joined_hosteluser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='reason',
            field=models.CharField(default='No reason provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
