# Generated by Django 5.1.4 on 2025-01-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leaveapplication_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='created_at',
        ),
    ]
